name: Update .env Versions

on:
  workflow_dispatch:
    inputs:
      backend_version:
        description: 'New backend version (e.g. 1.0)'
        required: false
      frontend_version:
        description: 'New frontend version (e.g. 2.0)'
        required: false

jobs:
  update-env:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client (just in case)
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host ${{ secrets.SSH_HOST }}\n\tStrictHostKeyChecking no\n\tUser ${{ secrets.SSH_USER }}" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Update .env file on server
        env:
          BACKEND_VERSION: ${{ inputs.backend_version }}
          FRONTEND_VERSION: ${{ inputs.frontend_version }}
        run: |
          ssh -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} '
            ENV_FILE="deploy/.env"

            # Проверяем, существует ли файл
            if [ ! -f "$ENV_FILE" ]; then
              echo "Файл $ENV_FILE не найден!"
              exit 1
            fi

            # Обновляем значения
            sed -i "s/^BACKEND_VERSION=.*/BACKEND_VERSION=$BACKEND_VERSION/" "$ENV_FILE"
            sed -i "s/^FRONTEND_VERSION=.*/FRONTEND_VERSION=$FRONTEND_VERSION/" "$ENV_FILE"

            echo "Успешно обновлено:"
            grep -E "^(BACKEND_VERSION|FRONTEND_VERSION)=" "$ENV_FILE"
          '
